name: default
modes: ["light", "dark"]
default_mode: "dark"
light:
  colors:
    background: [1.0, 0.0, 0.0]
    foreground: [0.145, 0.0, 0.0]
    card: [1.0, 0.0, 0.0]
    card_foreground: [0.145, 0.0, 0.0]
    popover: [1.0, 0.0, 0.0]
    popover_foreground: [0.145, 0.0, 0.0]
    primary: [0.205, 0.0, 0.0]
    primary_foreground: [0.985, 0.0, 0.0]
    secondary: [0.97, 0.0, 0.0]
    secondary_foreground: [0.205, 0.0, 0.0]
    muted: [0.97, 0.0, 0.0]
    muted_foreground: [0.556, 0.0, 0.0]
    accent: [0.97, 0.0, 0.0]
    accent_foreground: [0.205, 0.0, 0.0]
    destructive: [0.577, 0.245, 27.325]
    border: [0.922, 0.0, 0.0]
    input: [0.922, 0.0, 0.0]
    ring: [0.708, 0.0, 0.0]
    chart: [0.646, 0.222, 41.116]
    sidebar: [0.985, 0.0, 0.0]
    sidebar_foreground: [0.145, 0.0, 0.0]
    sidebar_primary: [0.205, 0.0, 0.0]
    sidebar_primary_foreground: [0.985, 0.0, 0.0]
    sidebar_accent: [0.97, 0.0, 0.0]
    sidebar_accent_foreground: [0.205, 0.0, 0.0]
    sidebar_border: [0.922, 0.0, 0.0]
    sidebar_ring: [0.708, 0.0, 0.0]
  icons:
    theme_mode_toggle: "\ue900"
dark:
  colors:
    background: [0.145, 0.0, 0.0]
    foreground: [0.985, 0.0, 0.0]
    card: [0.205, 0.0, 0.0]
    card_foreground: [0.985, 0.0, 0.0]
    popover: [0.205, 0.0, 0.0]
    popover_foreground: [0.985, 0.0, 0.0]
    primary: [0.922, 0.0, 0.0]
    primary_foreground: [0.205, 0.0, 0.0]
    secondary: [0.269, 0.0, 0.0]
    secondary_foreground: [0.985, 0.0, 0.0]
    muted: [0.269, 0.0, 0.0]
    muted_foreground: [0.708, 0.0, 0.0]
    accent: [0.269, 0.0, 0.0]
    accent_foreground: [0.985, 0.0, 0.0]
    destructive: [0.704, 0.191, 22.216]
    border: [1.0, 0.0, 0.0]
    input: [1.0, 0.0, 0.0] # Note: original input had alpha = 0.15
    ring: [0.556, 0.0, 0.0]
    chart: [0.488, 0.243, 264.376]
    sidebar: [0.205, 0.0, 0.0]
    sidebar_foreground: [0.985, 0.0, 0.0]
    sidebar_primary: [0.488, 0.243, 264.376]
    sidebar_primary_foreground: [0.985, 0.0, 0.0]
    sidebar_accent: [0.269, 0.0, 0.0]
    sidebar_accent_foreground: [0.985, 0.0, 0.0]
    sidebar_border: [1.0, 0.0, 0.0]
    sidebar_ring: [0.556, 0.0, 0.0]
  icons:
    theme_mode_toggle: "\ue901"
